DRIVER_CLASS=com.mysql.cj.jdbc.Driver
DB_USER=root
DB_CONNECTION_URL=jdbc:mysql://localhost/sugang?characterEncoding=utf8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
DB_PWD=gusdnr1919